version: "3.9"
services:
  client:
    container_name: client
    build: Client/
    stdin_open: true  
    tty: true 
    restart: unless-stopped
    networks:
      - br

  server:
    container_name: server
    build: Sppr/
    ports:
      - "5050:8080"
    restart: unless-stopped
    networks:
      - br

networks:
  br:
    driver: bridge